# Site settings
title: It's All Around
email: davidjerwin@gmail.com
description: > # It's All Around
baseurl: "" 
url: "http://itsallaround" 
twitter_username: daviderwin
github_username:  daviderwin

# Build settings
markdown: kramdown
